In [ ]:
import numpy as np
x= np.array([40,50,60,70])# damention
print(x.ndim)
identity = np.eye(2)
print(identity)
full=np.full((2,2),7)
print(full)
floating= np.array(([1,2],
                    [3,4]))
flo=np.float32(floating)
print(flo)
gap=np.arange(100,600,100)
print(gap)
x= np.array(([4,5],
              [6,7]))
y= np.array(([2,3],
             [5,6]))
print(x*y)# Multiplication
print(x*2)# Brodcast







1
[[1. 0.]
 [0. 1.]]
[[7 7]
 [7 7]]
[[1. 2.]
 [3. 4.]]
[100 200 300 400 500]
[[ 8 15]
 [30 42]]
[[ 8 10]
 [12 14]]


In [ ]:

import pandas as pd
dp=pd.read_csv("data.csv")
print(dp)
print(dp.tail)
print(dp.head)
print(dp.info)
print(dp.describe)


        name  age gender  marks        city              department
0        Ali   20      M     78      Lahore        Computer Science
1      Ahmed   21      M     85     Karachi    Software Engineering
2     Ayesha   19      F     88   Islamabad  Information Technology
3       Sara   22      F     91      Lahore        Computer Science
4     Hassan   20      M     67  Faisalabad  Electrical Engineering
5     Zainab   21      F     74      Multan  Information Technology
6      Usman   23      M     82  Rawalpindi    Software Engineering
7      Maria   20      F     90     Karachi        Computer Science
8    Huzaifa   22      M     69      Lahore       Civil Engineering
9       Iqra   19      F     95   Islamabad        Computer Science
10     Bilal   21      M     73      Multan  Electrical Engineering
11      Noor   20      F     89  Faisalabad  Information Technology
12      Saad   22      M     77  Rawalpindi    Software Engineering
13      Hina   23      F     84      Lahore     